title: TUM Info
author:
  name: Mykola Morozov
  email: mcmikecreations@gmail.com
description: >-
  A bunch of useful information I've collected while studying at the Technical University of Munich.
baseurl: "/tum_info"
url: ""
github_username:  mcmikecreations

# https://github.com/jekyll/minima
minima:
  skin: auto
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,         user_url: "https://github.com/mcmikecreations/tum_info" }
    - { platform: tum,            user_url: "https://www.tum.de/", title:  Official TUM website }

show_excerpts: false

header_pages:
  - about.md
  - pages/modules.html
  - pages/courses.html
  - pages/schools.html

collections:
  schools:
    code: "CIT"
    name: "School of Computation, Information and Technology"
    link: "https://www.cit.tum.de/en/"
    deps:
      - { code: "IN", link: "https://www.cs.cit.tum.de/en/", name: "Computer Science" }
    output: true
    permalink: /:collection/:path
  courses:
    school: "CIT"
    code: "IN0000"
    name: "Course name"
    semester: "2022WS" # refers to the year of the semester start
    exam_type: "endterm"
    ects: 0
    hours: 0 # semester hours
    mode: "written"
    lang: "en"
    date: "2022-01-01 12:00:00 +0100"
    grades:
      - { grade: 1.0, people: 1 }
    output: true
    permalink: /:collection/:path
  modules:
    school: "CIT"
    level: "MSc"
    name: "Informatics"
    semester:
      start: "2018SS"
      end: "2023SS"
    modules:
      - 
        name: "Algorithms (ALG)"
        courses:
        - 
          code: "IN0024"
          name: "Operations Research"
          credits: 6
          theo: true
          last: "2023SS"
          url: "https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950667748"
    output: true
    permalink: /:collection/:path

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

exclude:
  - .jekyll-cache/
